#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidLayoutPractice.Resource", IsApplication=true)]

namespace AndroidLayoutPractice
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int ScrollView1 = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int a = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int b = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button2 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int button_layout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button_layout2 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int c = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int d = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_layout2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_layout3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int a = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int action_settings = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int b = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int button1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int button2 = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int c = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int d = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int desc = 2130968597;
			
			// aapt resource value: 0x7f040005
			public const int gravity_right1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int gravity_right2 = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int hello_world = 2130968579;
			
			// aapt resource value: 0x7f040012
			public const int layout1 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int layout2 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int layout3 = 2130968596;
			
			// aapt resource value: 0x7f040007
			public const int text1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int text2 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text3 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int text4 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int text5 = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int title_activity_layout1 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int title_activity_layout2 = 2130968599;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
